[[headers]]
  for = "*.js" # js files should be set this way
  [headers.values]
    Cache-Control = "public, max-age=300"
[[headers]]
  for = "*.css" # css files too
  [headers.values]
    Cache-Control = "public, max-age=300"
[[headers]]
  for = "*.png" # css files too
  [headers.values]
    Cache-Control = "public, max-age=300"
[[headers]]
  for = "*.jpg" # css files too
  [headers.values]
    Cache-Control = "public, max-age=300"
[[headers]]
  for = "*.jpeg" # css files too
  [headers.values]
    Cache-Control = "public, max-age=300"